default:
    trainer: ppo
    batch_size: 40
    beta: 5.0e-3
    buffer_size: 100
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-5
    learning_rate_schedule: linear
    max_steps: 2000000
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 5000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    self_play:
        window: 10
        play_against_current_self_ratio: 0.5
        save_steps: 100000
        swap_steps: 20000

Sac:
    trainer: sac
    buffer_size: 5000
    buffer_init_steps: 256
    batch_size: 512
    init_entcoef: 0.5
    train_interval: 2
    num_update: 1
    tau: 0.005
    learning_rate: 1e-4
    learning_rate_schedule: constant
    time_horizon: 256
    normalize: false
    num_layers: 2
    max_steps: 500000
    hidden_units: 64
    vis_encode_type: simple
    use_recurrent: true
    sequence_length: 64
    memory_size: 16
    save_replay_buffer: false
    normalize: false
    summary_freq: 5000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    self_play:
        window: 10
        play_against_current_self_ratio: 0.5
        save_steps: 100000
        swap_steps: 20000
